version: '3.1'

services:

  db-dev:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nurota_blogs
    ports:
      - 5444:5432

  db-test:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: nurota_blogs
    ports:
      - 5445:5432
    